apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- paymentservice.yaml

images:
- name: paymentservice
  newName: 739022091869.dkr.ecr.ap-south-1.amazonaws.com/paymentservice
  newTag: "23"
