apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: dev
  labels:
    app: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      serviceAccountName: cartservice
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: cartservice
        image: 739022091869.dkr.ecr.ap-south-1.amazonaws.com/cartservice:10
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: cartservice-config
              key: redis_host
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 7070
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 7070