apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: dev
  labels:
    app: currencyservice
spec:
  selector:
    app: currencyservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000