apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- service-account.yaml
- Namespace.yaml
# - ingress.yaml

images:
- name: frontend
  newName: 739022091869.dkr.ecr.ap-south-1.amazonaws.com/frontend
  newTag: "68"
